#
# Copyright Â© 2025 Agora
# This file is part of TEN Framework, an open source project.
# Licensed under the Apache License, Version 2.0, with certain conditions.
# Refer to the "LICENSE" file in the root directory for more information.
#

[project]
name = "default-llm-extension-python"
description = "Default TEN Framework LLM extension template written in Python"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = ["websockets~=14.0", "pydantic", "requests"]

[tool.pytest.ini_options]
testpaths = ["tests"]
